Feature/multilevel dependencies
Vyro-ai/imagine-sdk-python pull request #2
Opened 2023-09-03 18:03 UTC by JustanAverageOtaku

Changes Made:
1. Added multilevel dependencies
2. Refactored code
3. Updated ReadMe
4. Changed the License

2023-09-03 19:15 UTC, UbadahJ requested changes
Please recheck the markdown with markdown formatter and pass it through the spell checker

2023-09-03 19:15 UTC, UbadahJ commented on README.md
> +if response.status is Status.OK:
Don't use is as it is intended to be used to object equality; Prefer ==

2023-09-03 19:15 UTC, UbadahJ commented on README.md
> +- **Alter-Image**: alter_image() -> Response[Image]
This is called guided generations, not alter image; Also mark this as not supported for now

2023-09-03 19:15 UTC, UbadahJ commented on README.md
> +- **In-Painting**: in_painting() -> Response[Image]
These are not currently supported.

Also, Variate is called variations

2023-09-03 19:15 UTC, UbadahJ commented on README.md
>  ### Some More Usage Examples:
Rather than this, please add sections for each method

2023-09-03 19:15 UTC, UbadahJ commented on README.md
> +```
Let people know that they can add each dependency individually

2023-09-03 19:15 UTC, UbadahJ commented on src/imagine/client.py
> +        m_ver: SuperResoultionStyle = SuperResoultionStyle.BASIC,
This variable needs updating and there is a spelling mistake

2023-09-03 19:15 UTC, UbadahJ commented on src/imagine/client.py
> +        model_version: InPaintingStyle = InPaintingStyle.BASIC,
Check the variable name

2023-09-03 19:15 UTC, UbadahJ commented on src/imagine/client.py
>          high_res_results: Optional[int] = None,
I think making it a boolean is better while auto mapping to 1 or 0 internally

2023-09-04 03:39 UTC, JustanAverageOtaku commented on src/imagine/client.py
> +        model_version: InPaintingStyle = InPaintingStyle.BASIC,
Can you point it out? I can't find it.

2023-09-05 07:44 UTC, UbadahJ requested changes

2023-09-05 07:44 UTC, UbadahJ commented on README.md
> +- **Guided-Generations**: `guided_generations() -> Response[Image]` (_Currently Not Supported_)
This has been deprecated, please remove

2023-09-05 07:44 UTC, UbadahJ commented on README.md
> +> To use this method you must have Pillow installed
It is better to phrase this as 

> If you installed `imaginesdk[all]`, you can skip the first step

First, get the dependency for PIL

```
pip install PIL
```

2023-09-05 09:50 UTC, UbadahJ approved these changes

2023-09-05 09:51 UTC, merged